- hosts: localhost
  become: yes
  force_handlers: true

  vars:
    - db_name: wordpress
    - db_user: wpadmin
    - db_pass: m4RFNPLnHYYEmHRG

  roles:
    - based
    - httpd
    - role: mariadb
      vars:
        database: "{{ db_name }}"
        username: "{{ db_user }}"
        password: "{{ db_pass }}"
    - role: wordpress
      vars:
        packages: wordpress-6.1-ja.tar.gz
        database: "{{ db_name }}"
        username: "{{ db_user }}"
        password: "{{ db_pass }}"