- hosts: localhost
  become: yes
  force_handlers: true

  roles:
    - based
    - httpd
    - role: mariadb
      vars:
        database: wordpress
        username: wpadmin
        password: password
    - role: wordpress
      vars:
        packages: wordpress-6.1-ja.tar.gz