- name: Enable amzn2-linux-extra php7.4 repository
  shell: amazon-linux-extras enable php7.4
  changed_when: false

- name: Install PHP
  yum:
    name:
      - php
      - php-pdo
      - php-mysqlnd
      - php-gd
      - php-mbstring
      - php-xml
      - php-pecl-json
      - glibc-langpack-ja
    state: present

- name: Download WordPress
  get_url:
    url: https://ja.wordpress.org/wordpress-5.7.1-ja.tar.gz
    dest: /tmp

- name: Unzip WordPress
  unarchive:
    src: /tmp/wordpress-5.7.1-ja.tar.gz
    dest: /var/www/html
    extra_opts: [--strip-components=1]

- name: Setup wp-config.php
  copy:
    src: /var/www/html/wp-config-sample.php
    dest: /var/www/html/wp-config.php
    mode: 0644

- name: Apply patch to wp-config.php
  patch:
    src: wp-config.php.patch
    dest: /var/www/html/wp-config.php

- name: chown -R apache:apache /var/www/html
  file:
    path: /var/www/html
    state: directory
    owner: apache
    group: apache
    recurse: yes

- name: Restart Apache
  service:
    name: httpd
    state: restarted